### ISSUE TITLE
[BUG/FEATURE] Disable "Open with JCE" on unauthorised sheets.

### ISSUE THREAD

**Issue by MrVauxs** [arcanistzed/jce#4]
**Describe the bug**
Players are able to open the JCE Editor on any sheet they have access to. While this is harmless as they cannot edit the sheet, they do and can read the entire HTML of it including the `<secret>` tags, which is obviously a breach of what that tag is supposed to do

**To Reproduce**
1. Create a journal
2. Right click and open JCE as another user who does not have writing permissions, only to view

**Expected behavior**
There is no button to open the JCE or at the very least, the button opens with a permission error, rather than have the code be shown.

**Foundry VTT version:**
Core Version: 0.8.7
System: dnd5e 1.3.5

**Comment by arcanistzed** [comment]
This is also an issue if you enable Autoopen, so I think my favorite solution would be to add a setting to for minimum permission level needed (i.e. Trusted, Assistant, GM) for the module's functions to be available.

Alternatively, I could also check permissions before opening and make an error message appear like you suggested, but I feel like that's messy. It might work well in tandem with the setting described above.

Unfortunately, I don't think I can easily selectively change the context menu for each document, since it's per sidebar tab, but I will look into this.

Thanks for bringing this to my attention

**Comment by arcanistzed** [comment]
It now only works for the GM
